GET /hello?tokens=1001 HTTP/1.1
Host: localhost:8081

###
# @name google
GET http://localhost:8081/api/v1/hello
X-tenant-id: google
###
# @name irembo
GET http://localhost:8081/api/v1/hello
X-tenant-id: irembo
###
# @name meta
GET http://localhost:8081/api/v1/hello
X-tenant-id: meta
###

